{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# WH-RDCC: Wiener-Hopf Residual Dynamic Channel Charting\n",
    "## Implementazione completa su DICHASUS\n",
    "\n",
    "**Autore**: Andrea Piroddi  \n",
    "**PhD**: University of Northampton — CAST Centre\n",
    "\n",
    "> **Prima di eseguire**: Runtime → Cambia tipo di runtime → GPU (T4)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 0. Mount Google Drive e Setup"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from google.colab import drive\n",
    "drive.mount('/content/drive')\n",
    "\n",
    "import os\n",
    "import numpy as np\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.nn.functional as F\n",
    "from torch.utils.data import Dataset, DataLoader\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.manifold import trustworthiness\n",
    "from scipy.spatial.distance import cdist\n",
    "from numpy.linalg import lstsq\n",
    "import json\n",
    "import subprocess\n",
    "import tensorflow as tf\n",
    "import requests\n",
    "import gzip\n",
    "import zlib\n",
    "\n",
    "# Configurazione percorsi\n",
    "PROJECT_DIR = '/content/drive/MyDrive/WH_RDCC'\n",
    "DATA_RAW = f'{PROJECT_DIR}/data_raw'\n",
    "DATA_OUT = f'{PROJECT_DIR}/data'\n",
    "FIGS_OUT = f'{PROJECT_DIR}/figures'\n",
    "\n",
    "os.makedirs(DATA_RAW, exist_ok=True)\n",
    "os.makedirs(DATA_OUT, exist_ok=True)\n",
    "os.makedirs(FIGS_OUT, exist_ok=True)\n",
    "\n",
    "print(f'Progetto: {PROJECT_DIR}')\n",
    "print(f'Data raw: {DATA_RAW}')\n",
    "print(f'Data out: {DATA_OUT}')\n",
    "print(f'Figures:  {FIGS_OUT}')\n",
    "\n",
    "# Verifica GPU\n",
    "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "print(f'\\nDevice: {device}')\n",
    "if torch.cuda.is_available():\n",
    "    print(f'GPU: {torch.cuda.get_device_name(0)}')\n",
    "    print(f'RAM GPU: {torch.cuda.get_device_properties(0).total_memory/1e9:.1f} GB')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Installazione dipendenze"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "!pip install -q crcmod seaborn scikit-learn\n",
    "\n",
    "print(f'PyTorch:    {torch.__version__}')\n",
    "print(f'TensorFlow: {tf.__version__}')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Preprocessing: Download DICHASUS"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Spec DICHASUS (ricostruita dalla documentazione ufficiale)\n",
    "SPEC = {\n",
    "    \"bandwidth\": 50000000.0,\n",
    "    \"fc\": 1272000000.0,\n",
    "    \"antennas\": [\n",
    "        {\"location\": [2.365, -5.5, 2.5], \"assignments\": [[24, 25, 26, 27], [28, 29, 30, 31]]},\n",
    "        {\"location\": [-6.0, -5.5, 2.5], \"assignments\": [[16, 17, 18, 19], [20, 21, 22, 23]]},\n",
    "        {\"location\": [-6.0, -13.0, 2.5], \"assignments\": [[8, 9, 10, 11], [12, 13, 14, 15]]},\n",
    "        {\"location\": [2.365, -13.0, 2.5], \"assignments\": [[0, 1, 2, 3], [4, 5, 6, 7]]},\n",
    "    ],\n",
    "}\n",
    "\n",
    "antenna_count = sum(sum(len(row) for row in ap[\"assignments\"]) for ap in SPEC[\"antennas\"])\n",
    "antenna_assignments = [ap[\"assignments\"] for ap in SPEC[\"antennas\"]]\n",
    "AP_pos = np.array([ap[\"location\"] for ap in SPEC[\"antennas\"]])\n",
    "\n",
    "print(f'Antenne totali: {antenna_count} (atteso: 32)')\n",
    "print(f'AP positions:\\n{AP_pos}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Download con resume\n",
    "BASE_API = 'https://darus.uni-stuttgart.de/api/access/datafile'\n",
    "\n",
    "FILES = {\n",
    "    'dichasus-cf02.tfrecords': '/:persistentId?persistentId=doi:10.18419/DARUS-2854/14',\n",
    "    'dichasus-cf03.tfrecords': '/:persistentId?persistentId=doi:10.18419/DARUS-2854/15',\n",
    "    'dichasus-cf04.tfrecords': '/:persistentId?persistentId=doi:10.18419/DARUS-2854/16',\n",
    "    'spec.json': '/:persistentId?persistentId=doi:10.18419/DARUS-2854/12',\n",
    "    'reftx-offsets-dichasus-cf0x.json': '/:persistentId?persistentId=doi:10.18419/DARUS-2854/13',\n",
    "}\n",
    "\n",
    "EXPECTED_GB = {\n",
    "    'dichasus-cf02.tfrecords': 4.5,\n",
    "    'dichasus-cf03.tfrecords': 5.5,\n",
    "    'dichasus-cf04.tfrecords': 10.3,\n",
    "    'spec.json': 0.0,\n",
    "    'reftx-offsets-dichasus-cf0x.json': 0.0,\n",
    "}\n",
    "\n",
    "def download_with_resume(url, dest, expected_gb):\n",
    "    existing = os.path.getsize(dest) if os.path.exists(dest) else 0\n",
    "    expected_bytes = expected_gb * 1e9\n",
    "    \n",
    "    if existing >= expected_bytes * 0.95:\n",
    "        print(f'  OK: {os.path.basename(dest)} ({existing/1e9:.2f} GB)')\n",
    "        return\n",
    "    \n",
    "    headers = {'Range': f'bytes={existing}-'} if existing > 0 else {}\n",
    "    mode = 'ab' if existing > 0 else 'wb'\n",
    "    \n",
    "    with requests.get(url, stream=True, timeout=120, headers=headers) as r:\n",
    "        if r.status_code == 416:\n",
    "            print(f'  File già completo')\n",
    "            return\n",
    "        r.raise_for_status()\n",
    "        \n",
    "        downloaded = existing\n",
    "        with open(dest, mode) as f:\n",
    "            for chunk in r.iter_content(chunk_size=16*1024*1024):\n",
    "                f.write(chunk)\n",
    "                downloaded += len(chunk)\n",
    "                print(f'\\r    {downloaded/1e9:.2f} GB', end='', flush=True)\n",
    "    print(f'\\n  Completato: {os.path.getsize(dest)/1e9:.2f} GB')\n",
    "\n",
    "print('Download file DICHASUS...')\n",
    "for fname, path in FILES.items():\n",
    "    dest = f'{DATA_RAW}/{fname}'\n",
    "    url = f'{BASE_API}{path}'\n",
    "    download_with_resume(url, dest, EXPECTED_GB[fname])\n",
    "\n",
    "# Salva spec.json\n",
    "with open(f'{DATA_RAW}/spec.json', 'w') as f:\n",
    "    json.dump(SPEC, f, indent=2)\n",
    "print('spec.json salvato.')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Preprocessing: TFRecord → NumPy chunks"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def load_calibrate(tfrecords_path, offsets_path):\n",
    "    \"\"\"Crea un dataset TFRecord calibrato e riordinato per antenne.\"\"\"\n",
    "    with open(offsets_path) as f:\n",
    "        offsets = json.load(f)\n",
    "    \n",
    "    def parse(proto):\n",
    "        record = tf.io.parse_single_example(proto, {\n",
    "            \"csi\": tf.io.FixedLenFeature([], tf.string, default_value=\"\"),\n",
    "            \"pos-tachy\": tf.io.FixedLenFeature([], tf.string, default_value=\"\"),\n",
    "            \"time\": tf.io.FixedLenFeature([], tf.float32, default_value=0),\n",
    "        })\n",
    "        csi = tf.ensure_shape(\n",
    "            tf.io.parse_tensor(record[\"csi\"], out_type=tf.float32),\n",
    "            (antenna_count, 1024, 2))\n",
    "        csi = tf.complex(csi[:,:,0], csi[:,:,1])\n",
    "        csi = tf.signal.fftshift(csi, axes=1)\n",
    "        pos = tf.ensure_shape(\n",
    "            tf.io.parse_tensor(record[\"pos-tachy\"], out_type=tf.float64), (3,))\n",
    "        return csi, pos, record[\"time\"]\n",
    "    \n",
    "    def calibrate(csi, pos, time):\n",
    "        sto = tf.tensordot(tf.constant(offsets[\"sto\"]),\n",
    "            2*np.pi*tf.range(tf.shape(csi)[1], dtype=tf.float32)/\n",
    "            tf.cast(tf.shape(csi)[1], tf.float32), axes=0)\n",
    "        cpo = tf.tensordot(tf.constant(offsets[\"cpo\"]),\n",
    "            tf.ones(tf.shape(csi)[1], dtype=tf.float32), axes=0)\n",
    "        csi = tf.multiply(csi, tf.exp(tf.complex(0.0, sto+cpo)))\n",
    "        return csi, pos, time\n",
    "    \n",
    "    def reorder(csi, pos, time):\n",
    "        csi = tf.stack([[tf.gather(csi, idx) for idx in arr]\n",
    "                        for arr in antenna_assignments])\n",
    "        return csi, pos, time\n",
    "    \n",
    "    ds = tf.data.TFRecordDataset(tfrecords_path)\n",
    "    ds = ds.map(parse, num_parallel_calls=tf.data.AUTOTUNE)\n",
    "    ds = ds.map(calibrate, num_parallel_calls=tf.data.AUTOTUNE)\n",
    "    ds = ds.map(reorder, num_parallel_calls=tf.data.AUTOTUNE)\n",
    "    return ds"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def process_tfrecord_to_chunks(tfrecords_path, offsets_path, chunk_size=500, every_n=5):\n",
    "    \"\"\"Processa un file TFRecord e salva chunk di NumPy.\"\"\"\n",
    "    fname = os.path.basename(tfrecords_path).replace('.tfrecords','')\n",
    "    print(f'\\n=== {fname} ===')\n",
    "    \n",
    "    ds = load_calibrate(tfrecords_path, offsets_path)\n",
    "    ds = ds.enumerate().filter(lambda i, _: i % every_n == 0).map(lambda i, v: v)\n",
    "    \n",
    "    csi_chunk, pos_chunk, time_chunk = [], [], []\n",
    "    chunk_idx = 0\n",
    "    total = 0\n",
    "    \n",
    "    for csi, pos, time in ds:\n",
    "        csi_flat = tf.reshape(csi, (antenna_count, 1024))\n",
    "        csi_ri = tf.stack([tf.math.real(csi_flat), tf.math.imag(csi_flat)], axis=-1)\n",
    "        \n",
    "        csi_chunk.append(csi_ri.numpy().astype(np.float32))\n",
    "        pos_chunk.append(pos.numpy()[:2].astype(np.float32))\n",
    "        time_chunk.append(float(time.numpy()))\n",
    "        \n",
    "        if len(csi_chunk) >= chunk_size:\n",
    "            out_prefix = f'{DATA_OUT}/{fname}_chunk{chunk_idx:04d}'\n",
    "            np.save(f'{out_prefix}_csi.npy', np.stack(csi_chunk))\n",
    "            np.save(f'{out_prefix}_pos.npy', np.stack(pos_chunk))\n",
    "            np.save(f'{out_prefix}_time.npy', np.array(time_chunk))\n",
    "            total += len(csi_chunk)\n",
    "            print(f'  Chunk {chunk_idx:04d} salvato — totale: {total}', end='\\r')\n",
    "            csi_chunk, pos_chunk, time_chunk = [], [], []\n",
    "            chunk_idx += 1\n",
    "    \n",
    "    if csi_chunk:\n",
    "        out_prefix = f'{DATA_OUT}/{fname}_chunk{chunk_idx:04d}'\n",
    "        np.save(f'{out_prefix}_csi.npy', np.stack(csi_chunk))\n",
    "        np.save(f'{out_prefix}_pos.npy', np.stack(pos_chunk))\n",
    "        np.save(f'{out_prefix}_time.npy', np.array(time_chunk))\n",
    "        total += len(csi_chunk)\n",
    "    \n",
    "    print(f'\\n  {fname}: {total} campioni in {chunk_idx+1} chunk')\n",
    "    return total"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Processa tutti e tre i dataset (esegui solo la prima volta)\n",
    "PATHS = [\n",
    "    {'tfrecords': f'{DATA_RAW}/dichasus-cf02.tfrecords',\n",
    "     'offsets': f'{DATA_RAW}/reftx-offsets-dichasus-cf02.json'},\n",
    "    {'tfrecords': f'{DATA_RAW}/dichasus-cf03.tfrecords',\n",
    "     'offsets': f'{DATA_RAW}/reftx-offsets-dichasus-cf03.json'},\n",
    "    {'tfrecords': f'{DATA_RAW}/dichasus-cf04.tfrecords',\n",
    "     'offsets': f'{DATA_RAW}/reftx-offsets-dichasus-cf04.json'},\n",
    "]\n",
    "\n",
    "for p in PATHS:\n",
    "    if os.path.exists(p['tfrecords']):\n",
    "        process_tfrecord_to_chunks(p['tfrecords'], p['offsets'])\n",
    "    else:\n",
    "        print(f\"File non trovato: {p['tfrecords']}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Assembly: Concatena chunk e split train/test"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def assemble_train_test(train_ratio=0.8):\n",
    "    \"\"\"Concatena tutti i chunk, ordina per timestamp, split train/test.\"\"\"\n",
    "    chunk_bases = sorted(set(\n",
    "        f.replace('_csi.npy','')\n",
    "        for f in os.listdir(DATA_OUT)\n",
    "        if '_chunk' in f and '_csi.npy' in f\n",
    "    ))\n",
    "    print(f'Chunk totali: {len(chunk_bases)}')\n",
    "    \n",
    "    csi_list, pos_list, time_list = [], [], []\n",
    "    for base in chunk_bases:\n",
    "        csi_list.append(np.load(f'{DATA_OUT}/{base}_csi.npy'))\n",
    "        pos_list.append(np.load(f'{DATA_OUT}/{base}_pos.npy'))\n",
    "        time_list.append(np.load(f'{DATA_OUT}/{base}_time.npy'))\n",
    "    \n",
    "    print('Assemblo e ordino...')\n",
    "    csi_all = np.concatenate(csi_list, axis=0)\n",
    "    pos_all = np.concatenate(pos_list, axis=0)\n",
    "    time_all = np.concatenate(time_list, axis=0)\n",
    "    \n",
    "    idx = np.argsort(time_all)\n",
    "    csi_all = csi_all[idx]\n",
    "    pos_all = pos_all[idx]\n",
    "    time_all = time_all[idx]\n",
    "    \n",
    "    k = int(len(csi_all) * train_ratio)\n",
    "    for prefix, sl in [('train', slice(None, k)), ('test', slice(k, None))]:\n",
    "        np.save(f'{DATA_OUT}/{prefix}_csi.npy', csi_all[sl])\n",
    "        np.save(f'{DATA_OUT}/{prefix}_positions.npy', pos_all[sl])\n",
    "        np.save(f'{DATA_OUT}/{prefix}_timestamps.npy', time_all[sl])\n",
    "        print(f'{prefix}: {csi_all[sl].shape}')\n",
    "    \n",
    "    # Salva posizioni AP\n",
    "    np.save(f'{DATA_OUT}/AP_pos.npy', AP_pos.astype(np.float32))\n",
    "    print('Assembly completato.')\n",
    "\n",
    "# Esegui assembly\n",
    "assemble_train_test()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Dataset PyTorch"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "class DICHASUSDataset(Dataset):\n",
    "    \"\"\"Dataset per WH-RDCC con sequenze temporali.\"\"\"\n",
    "    \n",
    "    def __init__(self, csi_path, pos_path, time_path,\n",
    "                 seq_len=16, stride=4, max_gap_ms=750):\n",
    "        self.csi = np.load(csi_path, mmap_mode='r')\n",
    "        self.positions = np.load(pos_path)\n",
    "        self.timestamps = np.load(time_path)\n",
    "        self.seq_len = seq_len\n",
    "        \n",
    "        # Costruisce lista di indici di sequenze valide\n",
    "        self.valid = []\n",
    "        for i in range(0, len(self.timestamps)-seq_len+1, stride):\n",
    "            gaps = np.diff(self.timestamps[i:i+seq_len]) * 1000\n",
    "            if np.all(gaps <= max_gap_ms) and np.all(gaps > 0):\n",
    "                self.valid.append(i)\n",
    "        print(f'  Sequenze valide: {len(self.valid)}')\n",
    "    \n",
    "    def __len__(self):\n",
    "        return len(self.valid)\n",
    "    \n",
    "    def __getitem__(self, idx):\n",
    "        s = self.valid[idx]\n",
    "        e = s + self.seq_len\n",
    "        csi = torch.from_numpy(self.csi[s:e].copy())  # (L, 32, 1024, 2)\n",
    "        pos = torch.from_numpy(self.positions[s:e])   # (L, 2)\n",
    "        return csi, pos"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Carica dataset\n",
    "print('Train:')\n",
    "train_ds = DICHASUSDataset(\n",
    "    f'{DATA_OUT}/train_csi.npy',\n",
    "    f'{DATA_OUT}/train_positions.npy',\n",
    "    f'{DATA_OUT}/train_timestamps.npy',\n",
    "    seq_len=16, stride=4, max_gap_ms=750\n",
    ")\n",
    "\n",
    "print('Test:')\n",
    "test_ds = DICHASUSDataset(\n",
    "    f'{DATA_OUT}/test_csi.npy',\n",
    "    f'{DATA_OUT}/test_positions.npy',\n",
    "    f'{DATA_OUT}/test_timestamps.npy',\n",
    "    seq_len=16, stride=4, max_gap_ms=750\n",
    ")\n",
    "\n",
    "train_loader = DataLoader(train_ds, batch_size=32, shuffle=True, num_workers=2, pin_memory=True)\n",
    "test_loader = DataLoader(test_ds, batch_size=32, shuffle=False, num_workers=2, pin_memory=True)\n",
    "\n",
    "print(f'\\nBatch train: {len(train_loader)}  test: {len(test_loader)}')\n",
    "csi_b, pos_b = next(iter(train_loader))\n",
    "print(f'CSI batch: {tuple(csi_b.shape)}')\n",
    "print(f'POS batch: {tuple(pos_b.shape)}')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. Architetture: Encoder e Residual Net"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "class CSIEncoder(nn.Module):\n",
    "    \"\"\"CNN encoder f_θ con L2 normalization.\"\"\"\n",
    "    \n",
    "    def __init__(self, latent_dim=8):\n",
    "        super().__init__()\n",
    "        self.latent_dim = latent_dim\n",
    "        \n",
    "        self.conv1 = nn.Sequential(\n",
    "            nn.Conv2d(2, 16, kernel_size=(1, 7), stride=(1, 2), padding=(0, 3)),\n",
    "            nn.BatchNorm2d(16), nn.ReLU())\n",
    "        self.conv2 = nn.Sequential(\n",
    "            nn.Conv2d(16, 32, kernel_size=(1, 7), stride=(1, 2), padding=(0, 3)),\n",
    "            nn.BatchNorm2d(32), nn.ReLU())\n",
    "        self.conv3 = nn.Sequential(\n",
    "            nn.Conv2d(32, 64, kernel_size=(1, 7), stride=(1, 2), padding=(0, 3)),\n",
    "            nn.BatchNorm2d(64), nn.ReLU())\n",
    "        self.conv4 = nn.Sequential(\n",
    "            nn.Conv2d(64, 64, kernel_size=(2, 7), stride=(2, 2), padding=(0, 3)),\n",
    "            nn.BatchNorm2d(64), nn.ReLU())\n",
    "        self.conv5 = nn.Sequential(\n",
    "            nn.Conv2d(64, 128, kernel_size=(2, 7), stride=(2, 4), padding=(0, 3)),\n",
    "            nn.BatchNorm2d(128), nn.ReLU())\n",
    "        \n",
    "        self.gap = nn.AdaptiveAvgPool2d((1, 1))\n",
    "        self.proj = nn.Sequential(\n",
    "            nn.Flatten(),\n",
    "            nn.Linear(128, 64),\n",
    "            nn.ReLU(),\n",
    "            nn.Linear(64, latent_dim)\n",
    "        )\n",
    "    \n",
    "    def forward(self, x):\n",
    "        # x: (B, 32, 1024, 2) → (B, 2, 32, 1024)\n",
    "        x = x.permute(0, 3, 1, 2)\n",
    "        for layer in [self.conv1, self.conv2, self.conv3, self.conv4, self.conv5]:\n",
    "            x = layer(x)\n",
    "        x = self.gap(x)\n",
    "        z = self.proj(x)\n",
    "        return F.normalize(z, dim=1)  # L2 normalization"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "class ResidualNet(nn.Module):\n",
    "    \"\"\"Residual net g_φ per la componente non lineare.\"\"\"\n",
    "    \n",
    "    def __init__(self, latent_dim=8, hidden_dim=64):\n",
    "        super().__init__()\n",
    "        self.net = nn.Sequential(\n",
    "            nn.Linear(latent_dim, hidden_dim),\n",
    "            nn.Tanh(),\n",
    "            nn.Linear(hidden_dim, hidden_dim),\n",
    "            nn.Tanh(),\n",
    "            nn.Linear(hidden_dim, latent_dim)\n",
    "        )\n",
    "    \n",
    "    def forward(self, z):\n",
    "        return self.net(z)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 7. Wiener-Hopf e Loss Functions"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def estimate_wiener_hopf(z_seq, eps=1e-4):\n",
    "    \"\"\"Stima closed-form di W* risolvendo equazione di Wiener-Hopf.\"\"\"\n",
    "    B, L, d = z_seq.shape\n",
    "    z_t = z_seq[:, :-1, :].reshape(-1, d)\n",
    "    z_tp1 = z_seq[:, 1:, :].reshape(-1, d)\n",
    "    \n",
    "    N = z_t.shape[0]\n",
    "    Rzz0 = (z_t.T @ z_t) / N\n",
    "    Rzz1 = (z_tp1.T @ z_t) / N\n",
    "    \n",
    "    reg = eps * torch.trace(Rzz0) / d\n",
    "    Rzz0_reg = Rzz0 + reg * torch.eye(d, device=z_seq.device)\n",
    "    \n",
    "    W = torch.linalg.lstsq(Rzz0_reg.T, Rzz1.T).solution.T\n",
    "    return W"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def contrastive_loss(z_seq, temperature=0.07):\n",
    "    \"\"\"NT-Xent loss (SimCLR-style) per channel charting.\"\"\"\n",
    "    B, L, d = z_seq.shape\n",
    "    z_a = z_seq[:, 0, :]  # anchor\n",
    "    z_p = z_seq[:, 1, :]  # positive (temporalmente vicino)\n",
    "    \n",
    "    z_all = torch.cat([z_a, z_p], dim=0)\n",
    "    sim = torch.mm(z_all, z_all.T) / temperature\n",
    "    \n",
    "    mask = torch.eye(2*B, device=z_seq.device).bool()\n",
    "    sim.masked_fill_(mask, -1e9)\n",
    "    \n",
    "    labels = torch.arange(B, device=z_seq.device)\n",
    "    labels = torch.cat([labels + B, labels])\n",
    "    \n",
    "    return F.cross_entropy(sim, labels)\n",
    "\n",
    "\n",
    "def wiener_hopf_loss(z_seq, W):\n",
    "    \"\"\"L_WH = ||z_{t+1} - W*z_t||^2\"\"\"\n",
    "    z_t = z_seq[:, :-1, :]\n",
    "    z_tp1 = z_seq[:, 1:, :]\n",
    "    pred = z_t @ W.T\n",
    "    return (z_tp1 - pred).pow(2).mean()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 8. Training Loop"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "@torch.no_grad()\n",
    "def extract_all_z_seq(encoder, loader, device):\n",
    "    \"\"\"Estrae tutte le sequenze latenti (per stima W*).\"\"\"\n",
    "    encoder.eval()\n",
    "    out = []\n",
    "    for csi_b, _ in loader:\n",
    "        B, L, a, s, c = csi_b.shape\n",
    "        z = encoder(csi_b.view(B*L, a, s, c).to(device))\n",
    "        out.append(z.view(B, L, -1))\n",
    "    return torch.cat(out, dim=0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def train_wh_rdcc(train_loader, latent_dim=8, lambda_wh=5.0,\n",
    "                  bootstrap_epochs=40, joint_epochs=100,\n",
    "                  wh_update_every=5, lr=1e-3, weight_decay=1e-4,\n",
    "                  device=None):\n",
    "    \"\"\"Two-phase training per WH-RDCC.\"\"\"\n",
    "    if device is None:\n",
    "        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "    \n",
    "    encoder = CSIEncoder(latent_dim).to(device)\n",
    "    residual = ResidualNet(latent_dim).to(device)\n",
    "    optimizer = torch.optim.Adam(\n",
    "        list(encoder.parameters()) + list(residual.parameters()),\n",
    "        lr=lr, weight_decay=weight_decay)\n",
    "    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(\n",
    "        optimizer, T_max=bootstrap_epochs+joint_epochs, eta_min=1e-5)\n",
    "    \n",
    "    W = torch.eye(latent_dim, device=device)\n",
    "    history = {'cc': [], 'wh': []}\n",
    "    \n",
    "